



export const TICKETS_LOADING="TICKETS_LOADING";
export const TICKETS_LOAD_SUCCES="TICKETS_LOAD_SUCCES";
export const TICKETS_LOAD_ERROR="TICKETS_LOAD_ERROR";


export const TICKET_LOADING="TICKET_LOADING";
export const TICKET_LOAD_SUCCES="TICKET_LOAD_SUCCES";
export const TICKET_LOAD_ERROR="TICKET_LOAD_ERROR";


export const CREATE_TICKET_LOADING="CREATE_TICKET_LOADING";
export const CREATE_TICKET_LOAD_SUCCES="CREATE_TICKET_LOAD_SUCCES";
export const CREATE_TICKET_LOAD_ERROR="CREATE_TICKET_LOAD_ERROR";